[package]
name = "process-api"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.61.1", features = ["Win32", "Win32_System", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug"] }